{% set name = "google-cloud-pubsub" %}
{% set version = "2.13.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-pubsub-{{ version }}.tar.gz
  sha256: e610fa3e2e793af884174b33703bba8fa304e2039cafef1d05d056e28849cc81

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-core-grpc >=1.32.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - grpcio >=1.38.1,<2.0dev
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    - grpc-google-iam-v1 >=0.12.4,<1.0.0dev
    - grpcio-status >=1.16.0
    # from libcst extra
    - libcst >=0.3.10

test:
  imports:
    - google.api_core
    - google.cloud.pubsub
    - grpc

about:
  home: https://pypi.org/project/google-cloud-pubsub/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python Client for Google Cloud Pub / Sub
  dev_url: https://github.com/googleapis/python-pubsub
  description: |
    Google Cloud Pub / Sub is a fully-managed real-time messaging service that
    allows you to send and receive messages between independent applications.
    You can leverage Cloud Pub/Sub’s flexibility to decouple systems and
    components hosted on Google Cloud Platform or elsewhere on the Internet. By
    building on the same technology Google uses, Cloud Pub / Sub is designed to
    provide “at least once” delivery at low latency with on-demand scalability
    to 1 million messages per second (and beyond).


extra:
  recipe-maintainers:
    - xylar
    - hmaarrfk
    - tpdownes
    - tswast
