{% set name = "google-cloud-pubsub" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d396ae1938e966e1ac3b981d14db7b0f9fabab553b0876c3202e187e4b477ab6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - google-api-core
    - grpc-google-iam-v1
    - enum34

test:
  imports:
    - google.cloud.pubsub_v1

about:
  home: https://pypi.org/project/google-cloud-pubsub/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python Client for Google Cloud Pub / Sub
  dev_url: https://github.com/googleapis/python-pubsub
  description: |
    Google Cloud Pub / Sub is a fully-managed real-time messaging service that
    allows you to send and receive messages between independent applications.
    You can leverage Cloud Pub/Sub’s flexibility to decouple systems and
    components hosted on Google Cloud Platform or elsewhere on the Internet. By
    building on the same technology Google uses, Cloud Pub / Sub is designed to
    provide “at least once” delivery at low latency with on-demand scalability
    to 1 million messages per second (and beyond).


extra:
  recipe-maintainers:
    - hmaarrfk
